version: "3.3"

services:

  prometheus:
    image: joja5627/prometheus:latest
    # container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - 9090:9090
    expose:
      - 9090

  frontend:
    image: joja5627/frontend:latest
    volumes:
      - ./stock-api/frontend:/frontend
    ports:
      - 3003:3003
    build: ./stock-api/frontend
    restart: unless-stopped
    command: npm run start
    expose:
     - 3003
    
  grafana:
    image: joja5627/grafana:latest
    # container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - 3002:3000
    expose:
      - 3002
      
  boto3-flask:
    image: joja5627/boto3-flask:latest
    build: ./python3-boto-env
    volumes:
      - ./python3-boto-env/app/:/app
    ports:
      - '5000:5000'
    
  mongodb:
    image: mongo:4.4.6
    # image: joja5627/mongo:latest
    restart: unless-stopped
    # container_name: mongodb
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    expose:
      - $MONGODB_LOCAL_PORT
    volumes:
      - db:/data/db

  algorithms-server:
    image: joja5627/node-server:latest
    build: ./stock-api
    restart: unless-stopped
    env_file: ./.env
    command: npm run algorithms-server
    volumes:
      - ./stock-api:/stock-api
    depends_on:
      - mongodb
    ports:
      - 3001:3001
    environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT

  scraping-server:
      image: joja5627/node-server:latest
      ports:
        - 3000:3000
      build: ./stock-api
      restart: unless-stopped
      env_file: ./.env
      command: npm run scraping-server
      volumes:
        - ./stock-api:/stock-api
      environment:
        - DB_USER=$MONGODB_USER
        - DB_PASSWORD=$MONGODB_PASSWORD
        - DB_NAME=$MONGODB_DATABASE
        - DB_PORT=$MONGODB_DOCKER_PORT

volumes:
  db:
  prometheus_data: 
  grafana_data: 

# docker-compose logs -f -t
# DB_HOST=54.202.122.11 docker build -t joja5627/node-server:latest  --build-arg MASTER_IP=54.202.122.11 
