version: "3.3"

services:

  scraping-server:
    image: joja5627/scraping-server:latest
    ports:
      - 3000:3000
    # build: ./stock-api
    restart: unless-stopped
    env_file: ./.env
    command: npm run scraping-server
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT

