global:
  scrape_interval: 5s
scrape_configs:
  - job_name: i-0b7dc66e635e74f4f
    static_configs:
      - targets:
          - 3.95.171.45:3000
  - job_name: i-046d4a45d2bbf178e
    static_configs:
      - targets:
          - 54.234.231.162:3000
  - job_name: i-0ea28c9ade73d3e7c
    static_configs:
      - targets:
          - 44.203.73.184:3000
  - job_name: i-0f51dbf94fb4695a6
    static_configs:
      - targets:
          - 3.87.67.222:3000
  - job_name: i-0eee2a11f7b94cdc6
    static_configs:
      - targets:
          - 35.173.231.29:3000
  - job_name: i-040c60969fb765591
    static_configs:
      - targets:
          - 3.84.211.135:3000
  - job_name: i-0c4043c001a1493d3
    static_configs:
      - targets:
          - 44.202.68.238:3000
  - job_name: i-0e48c90bb5bbc6530
    static_configs:
      - targets:
          - 3.85.131.255:3000
  - job_name: i-0c0670fd26a11d59e
    static_configs:
      - targets:
          - 54.173.94.25:3000
  - job_name: i-059f34b891f1f5309
    static_configs:
      - targets:
          - 18.234.187.112:3000
  - job_name: i-0db5243be1028716c
    static_configs:
      - targets:
          - 3.95.134.252:3000
  - job_name: i-05524521d058783ca
    static_configs:
      - targets:
          - 34.238.43.52:3000
  - job_name: i-07648fda10e188106
    static_configs:
      - targets:
          - 44.203.148.39:3000
  - job_name: i-0acec07fb15f5e9c0
    static_configs:
      - targets:
          - 44.202.251.76:3000
  - job_name: i-0969cc974ac25ed74
    static_configs:
      - targets:
          - 18.207.187.250:3000
  - job_name: i-0ec8929c0ffaa2d33
    static_configs:
      - targets:
          - 3.85.235.136:3000