global:
  scrape_interval: 5s
scrape_configs:
  - job_name: i-01386feaaf2ef673a
    static_configs:
      - targets:
          - 44.204.81.74:3000
  - job_name: i-022e2085d38a90106
    static_configs:
      - targets:
          - 18.206.54.159:3000
  - job_name: i-02bbf338a35bdca6d
    static_configs:
      - targets:
          - 44.211.198.50:3000
  - job_name: i-061e33154c670e57e
    static_configs:
      - targets:
          - 34.238.123.236:3000
  - job_name: i-07d5c06c2b49e8b2b
    static_configs:
      - targets:
          - 44.204.167.204:3000
  - job_name: i-062181ed8b7da9864
    static_configs:
      - targets:
          - 54.91.113.220:3000
  - job_name: i-0c2f7adc63a06a3a4
    static_configs:
      - targets:
          - 44.204.87.46:3000
  - job_name: i-0bc369e40ac9a400b
    static_configs:
      - targets:
          - 3.95.245.186:3000
  - job_name: i-030c96cd30b986771
    static_configs:
      - targets:
          - 44.208.35.195:3000
  - job_name: i-0b048ea6f30525e1d
    static_configs:
      - targets:
          - 52.90.220.129:3000
  - job_name: i-0fc2701688e8134fc
    static_configs:
      - targets:
          - 3.95.28.43:3000
  - job_name: i-0258cdb1ec629b20d
    static_configs:
      - targets:
          - 35.171.20.215:3000
  - job_name: i-037bfb3333abbdfc0
    static_configs:
      - targets:
          - 3.80.153.181:3000
  - job_name: i-02eaddf98aa83027e
    static_configs:
      - targets:
          - 44.205.254.188:3000
  - job_name: i-0c7a07c1f2105e4d0
    static_configs:
      - targets:
          - 44.203.87.44:3000
  - job_name: i-03a7d165f55211c1d
    static_configs:
      - targets:
          - 184.72.202.149:3000