global:
  scrape_interval: 5s
scrape_configs:
  - job_name: i-01386feaaf2ef673a
    static_configs:
      - targets:
          - 44.203.73.126:3000
  - job_name: i-022e2085d38a90106
    static_configs:
      - targets:
          - 34.239.119.96:3000
  - job_name: i-02bbf338a35bdca6d
    static_configs:
      - targets:
          - 34.201.52.151:3000
  - job_name: i-061e33154c670e57e
    static_configs:
      - targets:
          - 44.208.23.154:3000
  - job_name: i-07d5c06c2b49e8b2b
    static_configs:
      - targets:
          - 44.206.246.143:3000
  - job_name: i-062181ed8b7da9864
    static_configs:
      - targets:
          - 44.202.99.50:3000
  - job_name: i-0c2f7adc63a06a3a4
    static_configs:
      - targets:
          - 3.84.29.75:3000
  - job_name: i-0bc369e40ac9a400b
    static_configs:
      - targets:
          - 35.171.25.246:3000
  - job_name: i-030c96cd30b986771
    static_configs:
      - targets:
          - 54.162.79.51:3000
  - job_name: i-0b048ea6f30525e1d
    static_configs:
      - targets:
          - 18.234.188.93:3000
  - job_name: i-0fc2701688e8134fc
    static_configs:
      - targets:
          - 3.83.53.240:3000
  - job_name: i-0258cdb1ec629b20d
    static_configs:
      - targets:
          - 54.224.235.245:3000
  - job_name: i-037bfb3333abbdfc0
    static_configs:
      - targets:
          - 44.201.87.99:3000
  - job_name: i-02eaddf98aa83027e
    static_configs:
      - targets:
          - 54.210.1.8:3000
  - job_name: i-0c7a07c1f2105e4d0
    static_configs:
      - targets:
          - 44.205.253.243:3000
  - job_name: i-03a7d165f55211c1d
    static_configs:
      - targets:
          - 44.204.234.38:3000