const mongoose = require('mongoose');
var Schema = mongoose.Schema;



// "Market Cap (intraday)": 39010000,
// "Enterprise Value": -28660000,
// "Trailing P/E": 0,
// "Forward P/E": 0,
// "PEG Ratio (5 yr expected)": 0,
// "Price/Sales (ttm)": 27.99,
// "Price/Book (mrq)": 0.4,
// "Enterprise Value/Revenue": -20.8,
// "Enterprise Value/EBITDA": 0.81,
// "Beta (5Y Monthly)": 0.33,
// "52-Week Change": -0.6864,
// "S&P500 52-Week Change": -0.14730000000000001,
// "52 Week High": 5.15,
// "52 Week Low": 1.48,
// "50-Day Moving Average": 1.7496,
// "200-Day Moving Average": 2.3521,
// "Avg Vol (3 month)": 316680,
// "Avg Vol (10 day)": 51970,
// "Shares Outstanding": 25660000,
// "Implied Shares Outstanding": 0,
// "Float": 24300000,
// "% Held by Insiders": 0.052000000000000005,
// "% Held by Institutions": 0.1402,
// "Shares Short (Oct 30, 2022)": 427440,
// "Short Ratio (Oct 30, 2022)": 8.87,
// "Short % of Float (Oct 30, 2022)": 0.0176,
// "Short % of Shares Outstanding (Oct 30, 2022)": 0.0167,
// "Shares Short (prior month Sep 29, 2022)": 467600,
// "Forward Annual Dividend Rate": 0,
// "Forward Annual Dividend Yield": 0,
// "Trailing Annual Dividend Rate": 0,
// "Trailing Annual Dividend Yield": 0,
// "5 Year Average Dividend Yield": 0,
// "Payout Ratio": 0,
// "Dividend Date": null,
// "Ex-Dividend Date": 0,
// "Last Split Factor": null,
// "Last Split Date": null,
// "Fiscal Year Ends": null,
// "Most Recent Quarter (mrq)": null,
// "Profit Margin": 0,
// "Operating Margin (ttm)": -26.1998,
// "Return on Assets (ttm)": -0.16670000000000001,
// "Return on Equity (ttm)": -0.3507,
// "Revenue (ttm)": 1380000,
// "Revenue Per Share (ttm)": 0.05,
// "Quarterly Revenue Growth (yoy)": -0.889,
// "Gross Profit (ttm)": -16710000,
// "EBITDA": -34960000,
// "Net Income Avi to Common (ttm)": -39270000,
// "Diluted EPS (ttm)": -1.416,
// "Quarterly Earnings Growth (yoy)": 0,
// "Total Cash (mrq)": 69950000,
// "Total Cash Per Share (mrq)": 2.73,
// "Total Debt (mrq)": 2280000,
// "Total Debt/Equity (mrq)": 2.39,
// "Current Ratio (mrq)": 5.25,
// "Book Value Per Share (mrq)": 3.77,
// "Operating Cash Flow (ttm)": -28560000,
// "Levered Free Cash Flow (ttm)": -14500000



const scrapeSchema = new mongoose.Schema({
    id: Schema.Types.Mixed,
    name: Schema.Types.Mixed,
    lastsale: Schema.Types.Mixed,
    netchange: Schema.Types.Mixed,
    pctchange: Schema.Types.Mixed,
    volume: Schema.Types.Mixed,
    marketCap: Schema.Types.Mixed,
    country: Schema.Types.Mixed,
    ipoyear: Schema.Types.Mixed,
    industry: Schema.Types.Mixed,
    sector: Schema.Types.Mixed,
    url: Schema.Types.Mixed,
    symbol: Schema.Types.Mixed,
    maxAge: Schema.Types.Mixed,
    priceHint: Schema.Types.Mixed,
    enterpriseValue: Schema.Types.Mixed,
    forwardPE: Schema.Types.Mixed,
    profitMargins: Schema.Types.Mixed,
    floatShares: Schema.Types.Mixed,
    sharesOutstanding: Schema.Types.Mixed,
    sharesShort: Schema.Types.Mixed,
    sharesShortPriorMonth: Schema.Types.Mixed,
    sharesShortPreviousMonthDate: Schema.Types.Mixed,
    dateShortInterest: Schema.Types.Mixed,
    sharesPercentSharesOut: Schema.Types.Mixed,
    heldPercentInsiders: Schema.Types.Mixed,
    heldPercentInstitutions: Schema.Types.Mixed,
    shortRatio: Schema.Types.Mixed,
    shortPercentOfFloat: Schema.Types.Mixed,
    beta: Schema.Types.Mixed,
    category: Schema.Types.Mixed,
    bookValue: Schema.Types.Mixed,
    priceToBook: Schema.Types.Mixed,
    fundFamily: Schema.Types.Mixed,
    legalType: Schema.Types.Mixed,
    lastFiscalYearEnd: Schema.Types.Mixed,
    nextFiscalYearEnd: Schema.Types.Mixed,
    mostRecentQuarter: Schema.Types.Mixed,
    earningsQuarterlyGrowth: Schema.Types.Mixed,
    netIncomeToCommon: Schema.Types.Mixed,
    trailingEps: Schema.Types.Mixed,
    forwardEps: Schema.Types.Mixed,
    pegRatio: Schema.Types.Mixed,
    lastSplitFactor: Schema.Types.Mixed,
    enterpriseToRevenue: Schema.Types.Mixed,
    previousClose: Schema.Types.Mixed,
    open: Schema.Types.Mixed,
    dayLow: Schema.Types.Mixed,
    dayHigh: Schema.Types.Mixed,
    regularMarketPreviousClose: Schema.Types.Mixed,
    regularMarketOpen: Schema.Types.Mixed,
    regularMarketDayLow: Schema.Types.Mixed,
    regularMarketDayHigh: Schema.Types.Mixed,
    dividendRate: Schema.Types.Mixed,
    dividendYield: Schema.Types.Mixed,
    exDividendDate: Schema.Types.Mixed,
    payoutRatio: Schema.Types.Mixed,
    fiveYearAvgDividendYield: Schema.Types.Mixed,
    trailingPE: Schema.Types.Mixed,
    volume: Schema.Types.Mixed,
    regularMarketVolume: Schema.Types.Mixed,
    averageVolume: Schema.Types.Mixed,
    averageVolume10days: Schema.Types.Mixed,
    averageDailyVolume10Day: Schema.Types.Mixed,
    bid: Schema.Types.Mixed,
    ask: Schema.Types.Mixed,
    bidSize: Schema.Types.Mixed,
    askSize: Schema.Types.Mixed,
    marketCap: Schema.Types.Mixed,
    fiftyTwoWeekLow: Schema.Types.Mixed,
    fiftyTwoWeekHigh: Schema.Types.Mixed,
    forwardAnnualDividendRate: Schema.Types.Mixed,
    priceToSalesTrailing12Months: Schema.Types.Mixed,
    fiftyDayAverage: Schema.Types.Mixed,
    twoHundredDayAverage: Schema.Types.Mixed,
    trailingAnnualDividendRate: Schema.Types.Mixed,
    trailingAnnualDividendYield: Schema.Types.Mixed,
    currency: Schema.Types.Mixed,
    fromCurrency: Schema.Types.Mixed,
    lastMarket: Schema.Types.Mixed,
    algorithm: Schema.Types.Mixed,
    tradeable: Schema.Types.Mixed,
    currentPrice: Schema.Types.Mixed,
    targetHighPrice: Schema.Types.Mixed,
    targetLowPrice: Schema.Types.Mixed,
    targetMeanPrice: Schema.Types.Mixed,
    targetMedianPrice: Schema.Types.Mixed,
    recommendationMean: Schema.Types.Mixed,
    recommendationKey: Schema.Types.Mixed,
    numberOfAnalystOpinions: Schema.Types.Mixed,
    totalCash: Schema.Types.Mixed,
    totalCashPerShare: Schema.Types.Mixed,
    totalDebt: Schema.Types.Mixed,
    quickRatio: Schema.Types.Mixed,
    currentRatio: Schema.Types.Mixed,
    totalRevenue: Schema.Types.Mixed,
    debtToEquity: Schema.Types.Mixed,
    revenuePerShare: Schema.Types.Mixed,
    returnOnAssets: Schema.Types.Mixed,
    returnOnEquity: Schema.Types.Mixed,
    grossProfits: Schema.Types.Mixed,
    earningsGrowth: Schema.Types.Mixed,
    revenueGrowth: Schema.Types.Mixed,
    grossMargins: Schema.Types.Mixed,
    ebitdaMargins: Schema.Types.Mixed,
    operatingMargins: Schema.Types.Mixed,
    financialCurrency: Schema.Types.Mixed,
    recommendationTrend: Schema.Types.Mixed,
    closingHistories: Schema.Types.Mixed,
    maxAge: Schema.Types.Mixed,
    endDate: Schema.Types.Mixed,
    cash: Schema.Types.Mixed,
    shortTermInvestments: Schema.Types.Mixed,
    netReceivables: Schema.Types.Mixed,
    inventory: Schema.Types.Mixed,
    otherCurrentAssets: Schema.Types.Mixed,
    totalCurrentAssets: Schema.Types.Mixed,
    longTermInvestments: Schema.Types.Mixed,
    propertyPlantEquipment: Schema.Types.Mixed,
    goodWill: Schema.Types.Mixed,
    intangibleAssets: Schema.Types.Mixed,
    otherAssets: Schema.Types.Mixed,
    deferredLongTermAssetCharges: Schema.Types.Mixed,
    totalAssets: Schema.Types.Mixed,
    accountsPayable: Schema.Types.Mixed,
    otherCurrentLiab: Schema.Types.Mixed,
    longTermDebt: Schema.Types.Mixed,
    otherLiab: Schema.Types.Mixed,
    deferredLongTermLiab: Schema.Types.Mixed,
    minorityInterest: Schema.Types.Mixed,
    totalCurrentLiabilities: Schema.Types.Mixed,
    totalLiab: Schema.Types.Mixed,
    commonStock: Schema.Types.Mixed,
    retainedEarnings: Schema.Types.Mixed,
    treasuryStock: Schema.Types.Mixed,
    capitalSurplus: Schema.Types.Mixed,
    otherStockholderEquity: Schema.Types.Mixed,
    totalStockholderEquity: Schema.Types.Mixed,
    netTangibleAssets: Schema.Types.Mixed,
    tenYearGovtTreasuryYtm: Schema.Types.Mixed,
    yoyCPI: Schema.Types.Mixed,
    treasuryYieldCurve: Schema.Types.Mixed,
    tenYearTreasuryRate: Schema.Types.Mixed,
    tenYearTreasuryRateMonthly: Schema.Types.Mixed,
    tenYearTreasuryRateQuarterly: Schema.Types.Mixed,
    spyDividenYield: Schema.Types.Mixed,
    m1SeasonallyAdjustedLastMonth: Schema.Types.Mixed,
    m1SeasonallyAdjustedCurrent: Schema.Types.Mixed,
    lastMonthsWeeklyEarnings: Schema.Types.Mixed,
    currentWeeklyEarnings: Schema.Types.Mixed,
    forwardAnnualDividendRate: Schema.Types.Mixed,
    dilutedEPS: Schema.Types.Mixed,
    sAndPFiveHundredFiftyTwoWeekChange: Schema.Types.Mixed,
    fiftyTwoWeekChange: Schema.Types.Mixed,
    quarterlyRevenueGrowth: Schema.Types.Mixed,
    eps: Schema.Types.Mixed,
    shortPercentOfSharesOutstanding: Schema.Types.Mixed,
    currentAssets:Schema.Types.Mixed,
    currentLiabilities:Schema.Types.Mixed,
    previouslyIssuedShares:Schema.Types.Mixed,
    currentlyIssuedShares:Schema.Types.Mixed,
    operatingCashFlow:Schema.Types.Mixed,
    
},
    { timestamps: { createDate: 'created_at', updatedDate: 'updated_at' } });

const Scrape = mongoose.model('scrape', scrapeSchema);

module.exports = {
    Scrape
}
